### ISSUE TITLE
TouchFadeView not found

### ISSUE THREAD

**Issue by cbwalther1** [AndreiMisiukevich/TouchEffect#1]
Copied and pasted from your sample solution and I'm receiving exception when reaching page with the control.

> Type controls:TouchFadeView not found in xmlns clr-namespace:TouchEffect.Controls;assembly=TouchEffect

I have `xmlns:controls="clr-namespace:TouchEffect.Controls;assembly=TouchEffect"`
And then `<controls:TouchFadeView Padding="10, 5" BackgroundColor="Black" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Completed="Handle_TouchCompleted">
                        <Label Text="CLICK ME" TextColor="White" FontSize="60"/>
                    </controls:TouchFadeView>`

**Comment by AndreiMisiukevich** [comment]
@cbwalther1 hi
try next steps
1) Remove package from solution
2) Close VS
3) Delete all bin and obj folders
4) Open VS again
5) Add package again
6) Try to start

**Comment by cbwalther1** [comment]
Thank you for your very fast response!

I did that and still receiving same error. Performed a rebuild too just for kicks.

FYI - I added nuget to Shared Project and iOS project. Weird thing is, intellisense autofills `TouchFadeView` when I start typing `controls:`. But just can't find it during runtime.

**Comment by AndreiMisiukevich** [comment]
ok, could you please try next approach
in you main App.cs file, in constructor, write next line of code (before setting main page)

new TouchFadeView();

**Comment by AndreiMisiukevich** [comment]
probably, you will have to enable "link framework sdk assemblies"

**Comment by cbwalther1** [comment]
Wrote that code, no exceptions were thrown at that line, but same exception occurred when reaching page with the control. I also already had "link framework sdk assemblies" enabled

**Comment by cbwalther1** [comment]
I think it's because I don't have `TouchViewRenderer.Initialize();` in AppDelegate.cs. Will try that now

**Comment by cbwalther1** [comment]
Upon trying the above, I could not reference `TouchViewRenderer`. `using TouchEffect.iOS;` would not work because `TouchEffect` could not be found. I then found that the nuget wasn't showing in my iOS project's references... although it is installed through nuget manager. 

FYI - I am targeting .NET Standard 2.0

**Comment by AndreiMisiukevich** [comment]
Ok, I will check it today-tomorrow
Perhaps, I made a mistake in nuspec....

**Comment by cbwalther1** [comment]
Found temp solution. Went in iOS Project folder > bin > iPhone > debug and found TouchEffect.dll in there. I then manually made the iOS project reference the dll in VS. Now everything works.

**Comment by AndreiMisiukevich** [comment]
@cbwalther1 good job...
But I don't see any issues in nuspec file..
Hm, do you see this dll in iOS folder of packages folder?

**Comment by cbwalther1** [comment]
No its my iOS project's main folder...

Interesting... I've updated all my previous nugets and now when I install this, the nuget automatically pops up in references and I no longer need to reference the dll.

**Comment by AndreiMisiukevich** [comment]
Hmm, that is very strange
Could you please try it on fresh new solution?
