### ISSUE TITLE
Completed event is not fired in Android

### ISSUE THREAD

**Issue by ssotir** [AndreiMisiukevich/TouchEffect#11]
I've tried the 2.0.5 version samples. The image touchview although is seems to be clicked since the image is changed, the alert is never shown though. I believe it is a bug because the 2.0.3 version works fine.

**Comment by AndreiMisiukevich** [comment]
Thanks, i will check

**Comment by Tum4ik** [comment]
I also have faced with this problem. I've updated from 2.0.2 to 2.0.5 and Completed event has stopped to work.

**Comment by Tum4ik** [comment]
I've just checked: 2.0.4 is working.

**Comment by AndreiMisiukevich** [comment]
Yeah, I added TapGestureRecognizer.. need to remove

**Comment by AndreiMisiukevich** [comment]
I will fix it on this week

**Comment by AndreiMisiukevich** [comment]
@ssotir @Tum4ik check next version please :) (will be available soon)
