### ISSUE TITLE
[3.0.1] Effects not working on iOS unless I override the effect class.

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#14]
I've upgraded a project to use TouchEffect 3.0.1, and switched the control approach to the effect approach. 
- It works ok on Android, 
- Doesn't work on UWP (it kind of worked on v2 with the control approach, so I've fixed this by making my own effect file for UWP - see https://github.com/AndreiMisiukevich/TouchEffect/issues/9 ), 
**- Doesn't work on iOS. Tapping controls doesn't show the pressed color and doesn't trigger the completed event.**

I did a quick experiment by copying the original iOS effect file from this GitHub repo into my project, and when that is hooked up it works as expected.

So, I'm a bit confused - what could be wrong? Any ideas?

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao wow, super (Re uwp) please, make PR to my repository ))

**Comment by AndreiMisiukevich** [comment]
did you add this:

TouchEffectPreserver.Preserve()

to AppDelegate ?

**Comment by MitchBomcanhao** [comment]
oh. I didn't think the preserve would have any effect on my build configuration as linking isn't used in debug and on release builds we're only linking framework sdk only. 
I hadn't added that line in the android project either, and it worked fine, hence why I didn't think it could be the cause.

Thanks

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao hope you will make pr for UWP :)
