### ISSUE TITLE
[UWP] Navigating with the mouse back button can trigger completed event on control in underlying page 

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#17]
I've got a page with a stack of controls that use toucheffect completed event to navigate to a sub page.
If I then use the mouse's back button, and the cursor happens to be on top of a touchview enabled control on the previous page, it'll trigger that control's completed event and off it goes to a subpage again.

Have not yet had time to investigate any potential fixes or workarounds.

**Comment by AndreiMisiukevich** [comment]
would you like to debug, fix and make PR ? :)

**Comment by AndreiMisiukevich** [comment]
i am Mac user :(

**Comment by AndreiMisiukevich** [comment]
fixed https://github.com/AndreiMisiukevich/TouchEffect/pull/20
