### ISSUE TITLE
[UWP] Releasing a mouse button over a toucheffect control will trigger its completed event, regardless of where you started the click

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#18]
- Open any page with a control that has a toucheffect completed event associated with it.
- Move the mouse cursor to an empty location on the page.
- Press the mouse left button and then move the mouse cursor over the toucheffect control.
- EXPECTED:
-- Nothing happens because you've not actually clicked on the object.
- OBSERVED:
-- It will fire the completed event.

**Comment by AndreiMisiukevich** [comment]
would you like to debug, fix and make PR ? :)

**Comment by MitchBomcanhao** [comment]
I might have a fix for the most basic scenario, but now i'm finding some other edge cases where it'll break the plugin. I'll share more in a bit.

**Comment by AndreiMisiukevich** [comment]
fixed https://github.com/AndreiMisiukevich/TouchEffect/pull/20
