### ISSUE TITLE
Show ripple effect only if command is executed

### ISSUE THREAD

**Issue by mheydecke** [AndreiMisiukevich/TouchEffect#21]
Hi,
I use the effect and the command on a StackLayout in a BindableLayout.ItemTemplate.
The ripple effect is also shown if I touch the Item while scrolling within the view, but I only 
 want to show the ripple effect if the command is executed. Is this possible?

**Comment by AndreiMisiukevich** [comment]
@mheydecke hm, but it doesn't make sense to show effect only if command is executed. :) This library allow to make your UI responsive.

But if you wish, i can add some Delay property and ripple effect will appear only after delay in case of element is still pressed.

Does it work?

**Comment by mheydecke** [comment]
@AndreiMisiukevich 
thanks for the quick answer. You dont need to add an extra property. I was only curious if I was doing something wrong.

**Comment by AndreiMisiukevich** [comment]
cool)

**Comment by jhonatanfernando** [comment]
Hey.  What am I doing wrong?  I couldn't call the command from StackLayout.

```xaml
<StackLayout Grid.Column="1" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Margin="5"
                         touch:TouchEff.PressedBackgroundColor="{StaticResource TouchEffectButton}"
                         touch:TouchEff.CommandParameter="{Binding Path=PaxTappedCommandParameter, Source={x:Reference this}}"
                         touch:TouchEff.Command="{Binding Path=TappedCommand, Source={x:Reference this}}">
```

**Comment by AndreiMisiukevich** [comment]
> Hey. What am I doing wrong? I couldn't call the command from StackLayout.
> 
> ```
> <StackLayout Grid.Column="1" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Margin="5"
>                          touch:TouchEff.PressedBackgroundColor="{StaticResource TouchEffectButton}"
>                          touch:TouchEff.CommandParameter="{Binding Path=PaxTappedCommandParameter, Source={x:Reference this}}"
>                          touch:TouchEff.Command="{Binding Path=TappedCommand, Source={x:Reference this}}">
> ```

have you added TouchEff to StackLayout.Effects ?

**Comment by jhonatanfernando** [comment]
> @mheydecke hm, but it doesn't make sense to show effect only if command is executed. :) This library allow to make your UI responsive.
> But if you wish, i can add some Delay property and ripple effect will appear only after delay in case of element is still pressed.
> Does it work?

Hey @AndreiMisiukevich did you create the Delay property? Thanks.

**Comment by AndreiMisiukevich** [comment]
> > @mheydecke hm, but it doesn't make sense to show effect only if command is executed. :) This library allow to make your UI responsive.
> > But if you wish, i can add some Delay property and ripple effect will appear only after delay in case of element is still pressed.
> > Does it work?
> 
> Hey @AndreiMisiukevich did you create the Delay property? Thanks.

Hi, no, I didn't
