### ISSUE TITLE
[UWP] TouchEffect not working when app compiled with UseDotNetNativeToolchain=true

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#23]
When publishing an app to the windows store, it'll be recompiled with UseDotNetNativeToolchain set to true by Microsoft.

We can test this by building locally with `<UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>` in the Release build configuration, and so far my experience is that code that uses toucheffect doesn't work (ie I can click stuff and nothing happens - no errors, no ui changes).

I've set the `TouchEffectPreserver.Preserve();` line in the UWP project's app.xaml.cs file but no luck so far.

Has anyone else dealt with this issue?

**Comment by AndreiMisiukevich** [comment]
weird...
can you try to debug it on my samples?

**Comment by AndreiMisiukevich** [comment]
try to preserve them like

```csharp
new PlatformTouchEff();
new TouchEff();
```

in UWP code

**Comment by MitchBomcanhao** [comment]
I've just created a xamarin forms project with a uwp flavour and added this to its content.
It works fine if not using UseDotNetNativeToolchain. when used, it'll not apply the toucheffect bits.

```
        <ContentView touch:TouchEff.PressedAnimationDuration="750"
                     touch:TouchEff.PressedBackgroundColor="Red"
                     touch:TouchEff.RegularAnimationDuration="500"
                     touch:TouchEff.RegularBackgroundColor="Green"
                     touch:TouchEff.RippleCount="3">
            <ContentView.Effects>
                <touch:TouchEff Completed="TouchView_Completed" />
            </ContentView.Effects>
            <Label Margin="15" Text="try clicking on this label, it should turn from green to red" />
        </ContentView>
```
the code behind will have
```
private void TouchView_Completed(VisualElement sender, TouchEffect.EventArgs.TouchCompletedEventArgs args)
{
     // is this code reached in debug when not AOT compiled? yes!
}
```
and app.xaml.cs has
```
Xamarin.Forms.Forms.Init(e);

TouchEffectPreserver.Preserve();

var test1 = new PlatformTouchEff();
var test2 = new TouchEff();

System.Diagnostics.Trace.WriteLine($"TOUCHEFFECT 1 {test1.GetType().Assembly}");
System.Diagnostics.Trace.WriteLine($"TOUCHEFFECT 2 {test2.GetType().Assembly}");
```

which will output
```
TOUCHEFFECT 1 TouchEffect.UWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
TOUCHEFFECT 2 TouchEffect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```
but the touch effect will not be applied when clicking the ui element.

**Comment by MitchBomcanhao** [comment]
I've found something that makes it work - just not sure it is a good workaround. Had to add `using System.Reflection;` and then the following initialization for Xamarin forms in app.xaml.cs:

```
// For .NET Native compilation, you have to tell Xamarin.Forms which assemblies it should scan for custom controls and renderers 
var otherAssemblies = new[] 
{
    typeof(PlatformTouchEff).GetTypeInfo().Assembly
};
Xamarin.Forms.Forms.Init(e, otherAssemblies);
```

this was following an example from [https://www.mrgestures.com/#FAQs](url).
This might be problematic as it might conflict with the fixes for other packages which do similar things, but at least there's some progress.

**Comment by AndreiMisiukevich** [comment]
> I've found something that makes it work - just not sure it is a good workaround. Had to add `using System.Reflection;` and then the following initialization for Xamarin forms in app.xaml.cs:
> 
> ```
> // For .NET Native compilation, you have to tell Xamarin.Forms which assemblies it should scan for custom controls and renderers 
> var otherAssemblies = new[] 
> {
>     typeof(PlatformTouchEff).GetTypeInfo().Assembly
> };
> Xamarin.Forms.Forms.Init(e, otherAssemblies);
> ```
> 
> this was following an example from [https://www.mrgestures.com/#FAQs](url).
> This might be problematic as it might conflict with the fixes for other packages which do similar things, but at least there's some progress.

i think it's proper workaround

**Comment by MitchBomcanhao** [comment]
as a final comment, this is the bare minimum I've kept

```
Xamarin.Forms.Forms.Init(e, new[] { typeof(TouchEffect.UWP.PlatformTouchEff).Assembly });
```
no system.reflection needed.

on a project where I'm using rgplugins.popup, which also needs to be added to this list of assemblies, I've joined them up like so:
```
Rg.Plugins.Popup.Popup.Init();

Xamarin.Forms.Forms.Init(
    e,
    Rg.Plugins.Popup.Popup.GetExtraAssemblies().Concat(
        new[] { typeof(TouchEffect.UWP.PlatformTouchEff).Assembly })
    );
```

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao thanks) that's great
