### ISSUE TITLE
Revisting Content Page makes System.ObjectDisposedException exception.

### ISSUE THREAD

**Issue by ivoryguard** [AndreiMisiukevich/TouchEffect#24]
Hello.

I am trying to add Floating Action button with TouchImage control.

I created a XF 4.2 project with App Shell template.

I added FlyoutItems at AppShell.xaml like this;

```
    <FlyoutItem Title="Items Page">
        <ShellContent Title="Items Page" ContentTemplate="{DataTemplate local:ItemsPage}" />
    </FlyoutItem>

    <FlyoutItem Title="About Page">
        <ShellContent Title="About Page" ContentTemplate="{DataTemplate local:AboutPage}" />
    </FlyoutItem>
```

I added a TouchImage Button at ItemsPage like this;
```
       <Style x:Key="FabButonTouchImageStyle" TargetType="touch_effect:TouchImage">
            <Setter Property="HeightRequest" Value="64"/>
            <Setter Property="WidthRequest" Value="64"/>
            <Setter Property="Margin" Value="0,0,16,16" />
            <Setter Property="HorizontalOptions" Value="CenterAndExpand"/>
            <Setter Property="VerticalOptions" Value="CenterAndExpand"/>
        </Style>
...

<AbsoluteLayout VerticalOptions="End" HorizontalOptions="End">
            <touch_effect:TouchImage
                Style="{StaticResource FabButonTouchImageStyle}"
                RegularBackgroundImageSource="add_normal"
                PressedBackgroundImageSource="add_pressed"
                touch_effect:TouchEff.Command="{Binding AddItemCommand}"
                />
```

TouchImage Button works well at first.

However, System.ObjectDisposedException occurs when I go to About Page and go to Items Page again.

The detailed error message is as this;

```
System.ObjectDisposedException
Message=Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.
```

I suspect that TouchImage may be disposed on Disappearing Content Page.

As you know, XF does not recreate Content Page instance for Root Navigation Items at MasterDetail navigation and App Shell navigation.

How I can solve this issue?
Best regards.

Testing Environment:
Visual Studio 2019 16.3.2
Xamarin Forms 4.2.0.848062
TouchView 4.1.1

**Comment by AndreiMisiukevich** [comment]
Hi)
> Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer

this hints me that the crash appeared at Forms part.
Will you have the same crash if you change all touchEff to regular GestureRecognizer?

Also, can you prepare a small sample?

**Comment by AndreiMisiukevich** [comment]
@ivoryguard https://github.com/xamarin/Xamarin.Forms/issues/6754

**Comment by AndreiMisiukevich** [comment]
@ivoryguard can you provide a sample? I will report this issue to XF

**Comment by AndreiMisiukevich** [comment]
@ivoryguard are you still interested in fixing this bug?

**Comment by AndreiMisiukevich** [comment]
@ivoryguard I reproduced the bug

**Comment by AndreiMisiukevich** [comment]
I'll fix it locally and send PR with a fix to XF project

**Comment by AndreiMisiukevich** [comment]
v.4.1.3
