### ISSUE TITLE
Effects not working for Android.

### ISSUE THREAD

**Issue by kkohler2** [AndreiMisiukevich/TouchEffect#26]
It would be very helpful to have specific steps per platform to set up a working project, starting from scratch.  The sample app works, but I cannot get a new project to use the Effects in Android.  See my StackOverflow question: https://stackoverflow.com/questions/58650006/how-do-you-get-the-touchview-nuget-working-with-android-in-xamarin-android-proje

Documentation on how to set everything up for new projects to work with the nuget/library would be very helpful.

**Comment by AndreiMisiukevich** [comment]
Ah, what XF version do you use?

**Comment by AndreiMisiukevich** [comment]
It was XF issue, which I've already fixed https://github.com/xamarin/Xamarin.Forms/pull/6412

**Comment by AndreiMisiukevich** [comment]
wrap your Frame by ContentView or update XF version to the latest
