### ISSUE TITLE
[UWP] PointerCaptureLost should be handled

### ISSUE THREAD

**Issue by piersdeseilligny** [AndreiMisiukevich/TouchEffect#29]
On UWP, we should handle the `PointerCaptureLost` event, as explained by Microsoft in the custom user interactions guide:

![image](https://user-images.githubusercontent.com/42496508/69050207-68530780-09f9-11ea-9c0f-f5ad4b92ec1d.png)

Handling `PointerCaptureLost` would fix the situation of having a control with `TouchEff` inside a scrollview, where scrolling over the control causes it to keep it's `Pressed` status indefinitely, as such:

[![Demonstration](https://i.gyazo.com/4b39e99ba240f32c2aeb7da95edb7e9c.gif)](https://gyazo.com/4b39e99ba240f32c2aeb7da95edb7e9c)

Adding the following to PlatformTouchEff.cs fixes the issue partially:

```cs
private void OnPointerCaptureLost(object sender, PointerRoutedEventArgs e)
{
    Element.GetTouchEff().HandleTouch(TouchStatus.Canceled);
}
```
[![Partial fix](https://i.gyazo.com/2b6aacc85b60a782a5a941d156fd30d2.gif)](https://gyazo.com/2b6aacc85b60a782a5a941d156fd30d2)

However it introduces another issue: the hover state still remains active: setting `HoverState.Regular` in `OnPointerCaptureLost()` is not a viable solution, because `OnPointerCaptureLost()` is also called immediately after `OnPointerReleased()`, and losing the hover state after OnPointerReleased is not a desirable behaviour.

**Comment by piersdeseilligny** [comment]
(There is a similar undesirable pressed state persistence within Scrollviews on Android, which must also be resolved)

**Comment by AndreiMisiukevich** [comment]
> (There is a similar undesirable pressed state persistence within Scrollviews on Android, which must also be resolved)

check "dev" branch
I am working there

**Comment by AndreiMisiukevich** [comment]
Added mac hover support)
