### ISSUE TITLE
Not Working with Prism DelegateCommand ObservesCanExecute

### ISSUE THREAD

**Issue by rredoh** [AndreiMisiukevich/TouchEffect#3]
Hi Andrei, could you check if it's only me or u experience this to? In my use case is to prevent the image double clicked.

Example code :
```
private bool can_click = true;
public bool Can_Click{
   get{return can_click;}
   set{SetProperty(ref can_click, value);}
}
public DelegateCommand UpdateCommand=> new DelegateCommand(Update).ObservesCanExecute(()=> Can_Click);

private void Update(){
   Can_Click = false;
   //Do Something
   Can_Click = true;
}
```

**Comment by AndreiMisiukevich** [comment]
```csharp
private bool can_click = true;
public bool Can_Click{
   get{return can_click;}
   set{SetProperty(ref can_click, value);}
}

private DelegateCommand _updateCommand;
public DelegateCommand UpdateCommand => _updateCommand ?? ( _updateCommand = new DelegateCommand(Update).ObservesCanExecute(()=> Can_Click));

private void Update(){
   Can_Click = false;
   //Do Something
   Can_Click = true;
}
```

Hi, could you try this way?

I wait your feedback

**Comment by rredoh** [comment]
Yes. I tried it. It's still not working.

**Comment by AndreiMisiukevich** [comment]
@rredoh but it works with Xamarin.Forms Command, right?

**Comment by rredoh** [comment]
Yup. Everything works normally. I'm just curious why I can't protect it from double clicking if I use ObservesCanExecute.

**Comment by AndreiMisiukevich** [comment]
@rredoh good question :) have no idea yet

**Comment by rredoh** [comment]
Yup. Thanks for the response anyway :)

**Comment by AndreiMisiukevich** [comment]
@rredoh could you please create small sample project with this issue? I will try to find fix/workaround :)

**Comment by rredoh** [comment]
I'm sorry. My mistake. In the middle of making repro I realize that it happened in the middle of modal page animation. It's working normally if I turned off modal page animation

**Comment by AndreiMisiukevich** [comment]
@rredoh no problem) enjoy it. Thanks for feedback
P.S. If you like this plugin, you may set "STAR" =)

**Comment by rredoh** [comment]
Sure. Thanks for the time-saver plugin. Newbie here, and I love using this touch effect and cardview in my current project. Keep up the good work :)
