### ISSUE TITLE
Feature: Native tapping animations

### ISSUE THREAD

**Issue by piersdeseilligny** [AndreiMisiukevich/TouchEffect#31]
TouchEffect is very close to becoming the absolute perfect way to design custom buttons and inputs in Xamarin.Forms, however something which would truly make this library even more amazing than it already is, would be to support native animations.

An app with custom interactions, fonts, and buttons will look native (rather than like a web app) if it implements native tapping animations: It allows you to give a native feel to a non-native design.

In order to implement this, I'm suggesting that TouchEffect include a `NativeTapEffect` and `NativeTapEffectColor` property, which would enable:

* **Android:** Ripple animation, whose implementation can be inspired from [this Xamarin.Forms effect](https://github.com/mrxten/XamEffects/blob/master/src/XamEffects.Droid/TouchEffectPlatform.cs).

* **UWP**: `PointerDownThemeAnimation` and `PointerUpThemeAnimation`, details on how to implement these can be found [here](http://www.yortondotnet.com/2015/07/pointerdownthemeanimation.html).

* **Mac+iOS**: I'm not familliar with these platforms, but if there are any native animations which occur when tapping a UI Element, they should also be implemented

**Comment by AndreiMisiukevich** [comment]
sounds interesting..

**Comment by piersdeseilligny** [comment]
I suggest creating a new interface `INativeAnimation`, which would be used as a property (`NativeAnimation`) in `ITouchEff`. The following properties would then be accessed via `TouchEff.NativeAnimation`:

| Name | Type | Default value | Description |
|---|---|---|---|
| NativeAnimation.Enabled | `bool` | `false` | If native animations are created/played |
| NativeAnimation.Color | `Xamarin.Forms.Color` | `Color.White` | The color of the animation (on platforms where the animation uses a color) |
|   |   |   |   |
| NativeAnimation.Android.Enabled | `bool` | `true` | An override of `Enabled` for Android |
| NativeAnimation.Android.Color | `Xamarin.Forms.Color` | `null` | An override of `Color` for Android |
| NativeAnimation.Android.ZIndex | `NativeAnimation.Android.ZIndex` | `ZIndex.Foreground` | The location of the ripple effect: Foreground or Background |
| NativeAnimation.Android.Radius | `int` | `-1` | The radius of the Ripple animation | 
| NativeAnimation.Android.Bounded | `bool` | `true` | If the ripple animation uses `Container` as a mask (if not the ripple will extend beyond the bounds of the control) |
|   |   |   |   |
| NativeAnimation.UWP.Enabled | `bool` | `true` | An override of `Enabled` for UWP |
```

**Comment by AndreiMisiukevich** [comment]
looks good to me)

**Comment by piersdeseilligny** [comment]
Actually it would probably be simpler and more straightforward to implement these properties directly as properties of `TouchEff`
