### ISSUE TITLE
Cannot create a ripple effect

### ISSUE THREAD

**Issue by Mikilll94** [AndreiMisiukevich/TouchEffect#32]
I don't understand what does ripple count property. I was setting different values for ripple count but it does nothing. What I was expecting is that I can achieve a ripple effect like native buttons on Android but I think it is not possible.

Here is what I want to achieve:
![ripple](https://user-images.githubusercontent.com/17653648/69367482-afaaf380-0c98-11ea-9fea-cf35f1b0e82a.gif)

@AndreiMisiukevich 
Is it possible?

**Comment by piersdeseilligny** [comment]
This package currently doesn't support the Android ripple effect (the terminology is admittedly somewhat confusing). But it's funny that you should submit this issue today, as I've actually just been working on [adding support for native animations](https://github.com/AndreiMisiukevich/TouchEffect/issues/31), such as the ripple effect on Android.

**Comment by Mikilll94** [comment]
@piersdeseilligny 
Thanks for your response. This plugin is very useful in Xamarin development. But if there was be a possibility to add native animations to any layout, that would be awesome. No more button controls with very limited functionality!

BTW what does ripple count do? It looks like it does nothing.

**Comment by AndreiMisiukevich** [comment]
@Mikilll94 

please read the documentation first

```xaml
       <ContentView
            touch:TouchEff.PressedAnimationDuration="800"
            touch:TouchEff.RegularAnimationDuration="800"
            touch:TouchEff.PressedScale="0.9"
            touch:TouchEff.PressedOpacity="0.6"
            touch:TouchEff.RippleCount="-1"
            
            Padding="10, 5"
            BackgroundColor="Black"
            VerticalOptions="CenterAndExpand"
            HorizontalOptions="CenterAndExpand">
            
            <ContentView.Effects>
                <touch:TouchEff Completed="Handle_TouchCompleted"/>
            </ContentView.Effects>
            
            <Label Text="CLICK ME" 
                   TextColor="White" 
                   FontSize="60"/>
            
        </ContentView>
```

It allows making non-native ripple effect (but it works ONLY with other properties)

**Comment by Mikilll94** [comment]
@AndreiMisiukevich 
Here is your code in action.

![ripple_what](https://user-images.githubusercontent.com/17653648/69455245-47c3de00-0d68-11ea-8418-cfe5437c385b.gif)

To be honest, I don't see any ripple. You are just changing opacity and size. Where is the ripple?

**Comment by AndreiMisiukevich** [comment]
@Mikilll94 to be honest, you should press and hold, then you will see a ripple (pulsing)

**Comment by AndreiMisiukevich** [comment]
![Untitled](https://user-images.githubusercontent.com/10124814/69462369-d2690500-0d89-11ea-9316-cbcdea656408.gif)

**Comment by AndreiMisiukevich** [comment]
![Untitled_1](https://user-images.githubusercontent.com/10124814/69462434-0512fd80-0d8a-11ea-9617-cd980af9a876.gif)

**Comment by AndreiMisiukevich** [comment]
well, duplicated: https://github.com/AndreiMisiukevich/TouchEffect/issues/31
