### ISSUE TITLE
Android native touch effect may keep the pressed state when touch input moves away 

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#35]
Reporting against package version 4.1.19

I've found that if your control is in some sort of scrollable container, it'll not update the touch state as expected. I'm using the native effects but not sure if it is only related to those.

Example:
I tap and hold an item. it goes darker as expected.
I move the finger away from the item, but still touching the display. The item should exit the pressed state, and return to normal, but it does not.

```
    <ContentPage.Resources>
        <Style x:Key="TouchEffectBaseAndroid" TargetType="Grid">
            <Setter Property="touch:TouchEff.NativeAnimation" Value="True" />
        </Style>
    </ContentPage.Resources>

    <StackLayout>
        <Grid Style="{StaticResource TouchEffectBaseAndroid}">
            <Grid.Effects>
                <touch:TouchEff Completed="TouchEff_Completed" />
            </Grid.Effects>
            <StackLayout Padding="10">
                <Label FontSize="16" Text="This one is always OK" />
                <Label FontSize="13" Text="outside the scrollview" />
            </StackLayout>
        </Grid>
        <ScrollView>
            <Grid Style="{StaticResource TouchEffectBaseAndroid}">
                <Grid.Effects>
                    <touch:TouchEff Completed="TouchEff_Completed" />
                </Grid.Effects>
                <StackLayout Padding="10">
                    <Label FontSize="16" Text="This one is NOT ok" />
                    <Label FontSize="13" Text="inside the scrollview, will remain 'pressed'" />
                </StackLayout>
            </Grid>
        </ScrollView>
    </StackLayout>
```
On a page with this content, the top item will work as expected, the bottom one will not.

![ezgif-5-fdf0478c395a](https://user-images.githubusercontent.com/31066938/69744139-85917f80-1137-11ea-87da-cf928b9956c2.gif)

**Comment by AndreiMisiukevich** [comment]
Hi @piersdeseilligny
Would you like to take a look?)

**Comment by piersdeseilligny** [comment]
Will do when I've got time :) I don't think this is related to the native animations though.

**Comment by MitchBomcanhao** [comment]
Maybe the native animations merely make the underlying issue more obvious when we're not setting the pressed animations and colours ourselves.

**Comment by MitchBomcanhao** [comment]
On the bottom object, it doesn't seem to fire the expected Move events, so there's never an event outside the boundaries of the control and never an Up event, so there is no way to do the state reset.

This is likely due to the container of the control taking over the touch gestures...

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao yes, exactly.
I have a workaround for that.

**Comment by piersdeseilligny** [comment]
What's the workaround?

**Comment by AndreiMisiukevich** [comment]
set DisallowTouchThreshold to 20 or 25 or any another value:
```xaml
touch:TouchEff.DisallowTouchThreshold="20"
```

**Comment by MitchBomcanhao** [comment]
Only just had the chance of trying this change.

while the touchable control doesn't remain highlighted anymore using DisallowTouchThreshold when scrolling, it will still fire the android ripple animation, which is rather odd looking.
It also makes moving the finger within the control fire the ripple effect and not result in the intended action if the user lifts his finger.

These native animations are great and I really want to use them, just need to figure out how I can get it to work properly via config or code changes to the toucheffect package :)

**Comment by AndreiMisiukevich** [comment]
No idea how to improve it.
