### ISSUE TITLE
Typo in NuGet description

### ISSUE THREAD

**Issue by Mikilll94** [AndreiMisiukevich/TouchEffect#36]
![image](https://user-images.githubusercontent.com/17653648/70812847-b248c680-1dc8-11ea-82b5-90ac3d47b888.png)

**Comment by AndreiMisiukevich** [comment]
Hi, would you like to fix it?
https://github.com/AndreiMisiukevich/TouchEffect/blob/master/TouchEffect.nuspec

**Comment by piersdeseilligny** [comment]
It could also be useful to specify "during touch and hover interaction" rather than just "during touch interaction"

**Comment by AndreiMisiukevich** [comment]
Yes, feel free to make a PR

**Comment by Mikilll94** [comment]
@AndreiMisiukevich 
I have created a pull request #38
