### ISSUE TITLE
No native animation on iOS?

### ISSUE THREAD

**Issue by Mikilll94** [AndreiMisiukevich/TouchEffect#37]
Hey, do you plan to add any native animation on iOS? On Android this ripple is awesome, but on iOS nothing happens when you add:

```
touch:TouchEff.NativeAnimation="True"
```

IMO native animation on iOS should work, i.e. like this:

![ios_native_animation](https://user-images.githubusercontent.com/17653648/70929134-ac561e00-2032-11ea-99ae-e6fddf71646b.gif)

**Comment by AndreiMisiukevich** [comment]
@Mikilll94, of course, we will !)

**Comment by AndreiMisiukevich** [comment]
4.1.23

**Comment by Mikilll94** [comment]
@AndreiMisiukevich 
Thanks a lot!!! :)
