### ISSUE TITLE
Add LongPressed event / Command

### ISSUE THREAD

**Issue by scriptBoris** [AndreiMisiukevich/TouchEffect#39]
Good day, is it possible to implement using your nugetPackage method triggering with a long press hold?

If so, can this be done using NativeAnimation?

rus: Привет, можно ли реализовать с помощью вашего nugetPackage срабатывание метода при долгом удержании нажатия?
Если да, то можно ли это сделать с помощью NativeAnimation ?

**Comment by AndreiMisiukevich** [comment]
Hi, no, it is not possible now.

So, the long-press gesture can be added of course, but I didn't understand, how does NativeAnimation correlate with it?

**Comment by scriptBoris** [comment]
1) It is unfortunate that this is not possible.

2) I just thought that NativeAnimation has its own touch detection system.

**Comment by AndreiMisiukevich** [comment]
@scriptBoris but we still can add LongPressed event / command etc.

**Comment by scriptBoris** [comment]
@AndreiMisiukevich can you do this?

**Comment by AndreiMisiukevich** [comment]
I think yes
But if you wish, you can assist me :) (with UWP or Android haha)

**Comment by AndreiMisiukevich** [comment]
I decided to defer this enhancement.
Frankly speaking, I am not even sure that it should be implemented within this nuget
