### ISSUE TITLE
[Android] MotionEventActions.Move is not handled correctly

### ISSUE THREAD

**Issue by Huaba93** [AndreiMisiukevich/TouchEffect#46]
### Description
When leaving the vertical bounds of the VisualElement, the VisualElement is not reset.
It is working horizontally. 

### Steps to Reproduce

1.  Add Toucheffect
2.  Touch + move vertically far enough to leave bounds

### Expected Behavior
Command is not executed and control is reset to regular values. 

### Actual Behavior
Command is not executed but pressed values are not reset to regular values. 

### Basic Information
Tested with Samsung Galaxy S10 (Android 10)

### Screencast
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21239003/78875728-9f7c9080-7a4e-11ea-9801-762d3778392a.gif)

**Comment by AndreiMisiukevich** [comment]
Hi, Is your button inside a scrollview or listview ?

**Comment by Huaba93** [comment]
The button is inside a ScrollView. 
Outside of ScrollView it is working as expected. 

Haven't tested it with ListView or CollectionView

**Comment by AndreiMisiukevich** [comment]
@Huaba93 try to set DisallowTouchThreshold = 10, it will make it slightly better

**Comment by Huaba93** [comment]
Setting it to 10 makes it better for vertical scrolling but worse for horizontal. 
But this is good enough for me atm. 

I bind it to the buttons height.

**Comment by AndreiMisiukevich** [comment]
Yeah, I know. But don't know how to fix this yet.

**Comment by Huaba93** [comment]
Ok no problem, as i told, it is good enough ;)
Thanks for your help and thanks for the whole project. 
It was very easy and went very fast to replace most of the TapGestureRecognizer with the TouchEffect. The app feels now much more responsive. It's a huge UX improvement!

**Comment by AndreiMisiukevich** [comment]
@Huaba93 thanks, mate :)

**Comment by Huaba93** [comment]
Same problem on iOS. I used a collectionView. Any idea?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/21239003/79250326-c25bda00-7e7e-11ea-82c4-b169f348f2f9.gif)

**Comment by AndreiMisiukevich** [comment]
> Same problem on iOS. I used a collectionView. Any idea?
> 
> ![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/21239003/79250326-c25bda00-7e7e-11ea-82c4-b169f348f2f9.gif)

try to set DisallowTouchThreshold = 10

**Comment by Huaba93** [comment]
this only works for Android, not iOS

**Comment by AndreiMisiukevich** [comment]
> this only works for Android, not iOS

It should work for iOS as well
DisallowTouchThreshold = 1

?

**Comment by AndreiMisiukevich** [comment]
> this only works for Android, not iOS

try latest (no need to set DisallowTouchThreshold for iOS)

**Comment by AndreiMisiukevich** [comment]
hi @Huaba93 https://github.com/AndreiMisiukevich/TouchEffect/issues/51

**Comment by Huaba93** [comment]
I had no time to test, but I will soon ;)
