### ISSUE TITLE
What about supporting Ripple effects to all controls ?

### ISSUE THREAD

**Issue by SagarPanwala** [AndreiMisiukevich/TouchEffect#5]

**Comment by AndreiMisiukevich** [comment]
Hi
Have you got any example, what do you mean?

**Comment by SagarPanwala** [comment]
If you touch on button or listitem in android, you will see smooth effect.

You can see
https://youtu.be/6-lhXas634g

I'm not saying about how he code, just effect on listitem.

**Comment by AndreiMisiukevich** [comment]
Hi, new release has got breaking changes
You should use TouchView (more info in Readme file on main page of the project)

Use FadeDuration/FadeEasing/RecoverDuration/RecoverEasing for achieving the same behavior :)

**Comment by SagarPanwala** [comment]
Can you please give an example code?

**Comment by AndreiMisiukevich** [comment]
```xml
        <touch:TouchView
            FadeDuration="250"
            RecoverDuration="250"             
            Completed="Handle_TouchCompleted">

            <Label Text="CLICK ME" />

        </touch:TouchView>
```

Play with:
- FadeDuration
- RecoverDuration
- FadeEasing
- RecoverEasing
- PressedOpacity

**Comment by AndreiMisiukevich** [comment]
```xml
       <touch:TouchView
            PressedAnimationDuration="800"
            RegularAnimationDuration="800"
            RippleCount="-1"
            Padding="10, 5"
            BackgroundColor="Black"
            VerticalOptions="CenterAndExpand"
            HorizontalOptions="CenterAndExpand"
            Completed="Handle_TouchCompleted">

            <Label Text="CLICK ME" 
                   TextColor="White" 
                   FontSize="60"/>
            
        </touch:TouchView>
```

Will be available in the next release

**Comment by SagarPanwala** [comment]
Thanks alot,
Can we put any view inside touchview?

**Comment by AndreiMisiukevich** [comment]
@SagarPanwala yes, sure
TouchView is AbsoluteLayout
