### ISSUE TITLE
Support hover animation API

### ISSUE THREAD

**Issue by YZahringer** [AndreiMisiukevich/TouchEffect#50]
I see that the [API for hover animation](https://github.com/AndreiMisiukevich/TouchEffect/commit/92a66ce9476950a3b0e3588fc17c62529b03209e) support has been added but it's not implemented. Is this planned?

This would be very useful, it avoids using DataTriggers or events to manage simple visual effects.

**Comment by AndreiMisiukevich** [comment]
Good question. I think I should add hover support.
