### ISSUE TITLE
[UWP] Completed event raised twice when clicking on 

### ISSUE THREAD

**Issue by MitchBomcanhao** [AndreiMisiukevich/TouchEffect#52]
Running current release 4.1.36

I've noticed that the Completed event is now firing twice on TouchEff enabled controls, eg when clicking with the mouse.
eg 
```
<ContentView>
   <ContentView.Effects>
    <touch:TouchEff Completed="TouchView_Completed" />
  </ContentView.Effects>
</ContentView>
```

they both have the same stack
![image](https://user-images.githubusercontent.com/31066938/80976719-ad3def80-8e1b-11ea-8cbb-0d7af5f830a7.png)

Any ideas on what is going on?

**Comment by AndreiMisiukevich** [comment]
Workaround: switch to Command (and totally remove 
```
<ContentView.Effects>
    <touch:TouchEff Completed="TouchView_Completed" />
  </ContentView.Effects>
```
)

**Comment by AndreiMisiukevich** [comment]
CI/CD is building a new version :) will be available on nuget in 30 mins or even less

**Comment by MitchBomcanhao** [comment]
I've just tried the new package - was it supposed to allow me to continue with existing code or just a tidy up for other stuff you've noticed? I'm still seeing the same behaviour on UWP (have not tried others yet)

**Comment by AndreiMisiukevich** [comment]
> I've just tried the new package - was it supposed to allow me to continue with existing code or just a tidy up for other stuff you've noticed? I'm still seeing the same behaviour on UWP (have not tried others yet)

No, you can go ahead with your approach (With completion)

That's strange.

Well, if you switch to Command, does it fire event twice as well?

**Comment by AndreiMisiukevich** [comment]
Seems I know what the reason
I will fix it later
