### ISSUE TITLE
[iOS] Null reference exception with view change

### ISSUE THREAD

**Issue by bohbra** [AndreiMisiukevich/TouchEffect#54]
I get the following error when I use the command to change the view.  This is similar to issue #44.

```
{System.NullReferenceException: Object reference not set to an instance of an object
  at TouchEffect.iOS.TouchUITapGestureRecognizer.HandleTouch (TouchEffect.Enums.TouchStatus status) [0x0004d] in C:\GitHub\TouchEffect\TouchEffect.iOS\PlatformTouchEff.cs:153 
  at TouchEffect.iOS.TouchUITapGestureRecognizer.TouchesEnded (Foundation.NSSet touches, UIKit.UIEvent evt) [0x00012] in C:\GitHub\TouchEffect\TouchEffect.iOS\PlatformTouchEff.cs:85 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at App.iOS.Application.Main (System.String[] args) [0x00001] in C:\GitHub\TouchEffect\App\App.iOS\Main.cs:17 }	System.NullReferenceException
```

See example [here](https://github.com/bohbra/TouchEffect)

**Comment by Brayanhenaor** [comment]
I have the same bug with last version if I use toucheff:TouchEff.Command

**Comment by AndreiMisiukevich** [comment]
> A have the same bug with last version if I use toucheff:TouchEff.Command

Let me check...

**Comment by AndreiMisiukevich** [comment]
@Brayanhenaor cannot reproduce on iOS.
Can you please build a sample?

**Comment by AndreiMisiukevich** [comment]
> I have the same bug with last version if I use toucheff:TouchEff.Command

provide a sample please if you want to get this bug fixed. Unfortunately, I cannot reproduce it

**Comment by taieb1919** [comment]
> > I have the same bug with last version if I use toucheff:TouchEff.Command
> 
> provide a sample please if you want to get this bug fixed. Unfortunately, I cannot reproduce it

her a sample
   touch:TouchEff.Command="{Binding GoToMenuCommand}"
            touch:TouchEff.IsAvailable="True"
            touch:TouchEff.PressedBackgroundColor="Black"
            touch:TouchEff.PressedOpacity="8"
            touch:TouchEff.PressedScale="2"
            touch:TouchEff.RegularAnimationDuration="300"
            touch:TouchEff.RippleCount="1"

**Comment by AndreiMisiukevich** [comment]
> > > I have the same bug with last version if I use toucheff:TouchEff.Command
> > 
> > 
> > provide a sample please if you want to get this bug fixed. Unfortunately, I cannot reproduce it
> 
> her a sample
> touch:TouchEff.Command="{Binding GoToMenuCommand}"
> touch:TouchEff.IsAvailable="True"
> touch:TouchEff.PressedBackgroundColor="Black"
> touch:TouchEff.PressedOpacity="8"
> touch:TouchEff.PressedScale="2"
> touch:TouchEff.RegularAnimationDuration="300"
> touch:TouchEff.RippleCount="1"

Unfortunately, it's not a sample. That's just several lines of xaml markup.

What kind of view should I apply it to? (ContentView, Label, Frame, StackLayoyt ... ?)

**Comment by AndreiMisiukevich** [comment]
Can you build a small sample project where I can reproduce this issue?) Thanks

**Comment by AndreiMisiukevich** [comment]
Are you sure you update TouchView nuget in both iOS and netstandard projects?

**Comment by AndreiMisiukevich** [comment]
BTW, I have a couple of remarks about it:
```
touch:TouchEff.Command="{Binding GoToMenuCommand}"
touch:TouchEff.IsAvailable="True"
touch:TouchEff.PressedBackgroundColor="Black"
touch:TouchEff.PressedOpacity="8"
touch:TouchEff.PressedScale="2"
touch:TouchEff.RegularAnimationDuration="300"
touch:TouchEff.RippleCount="1"
```

```touch:TouchEff.IsAvailable="True"``` This is the default value. So you can remove this line.
```touch:TouchEff.PressedOpacity="8"``` Maximum opacity is 1. Wha does 8 mean? Maybe you wanted to set "0.8"?

**Comment by AndreiMisiukevich** [comment]
Well, please try latest version (but make sure you installed the LATEST version to both iOS and Netstandard projects). Perhaps I fixed this issue.
