### ISSUE TITLE
iPadOS Pointer support

### ISSUE THREAD

**Issue by piersdeseilligny** [AndreiMisiukevich/TouchEffect#55]
I'm not very familiar with iOS development, but iPadOS 13.4 has recently added support for [Pointer Interactions](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/pointers/). The API not only adds support for hovering, but also iPad-specific effects (such as "lift" and "highlight" which tbh seems slightly gimmicky).

I think it would make sense to at least add support for hover on iOS, with the usual `HoverState` used on Android and UWP. For the iPad specific-effects, they could potentially be implemented through `NativeHoverAnimation` or something along those lines, but because no equivalent really exists on other platforms, maybe it should be left to some other library.

**Comment by AndreiMisiukevich** [comment]
Hmm, not sure it's useful

**Comment by AndreiMisiukevich** [comment]
But as enhancement -- why not

**Comment by AndreiMisiukevich** [comment]
Feel free to make PR if you wish.
I think it won't be supported.
