### ISSUE TITLE
I try use this nuget but not working

### ISSUE THREAD

**Issue by Brayanhenaor** [AndreiMisiukevich/TouchEffect#56]
Hi.

I installed the nuget on my all projects, and add the Line _TouchEffectPreserver.Preserve()_ then tried the examples you have by, copying and pasting them into my project, so the animations not working. Am I missing something to add something else?

I appreciate your guidance

**Comment by AndreiMisiukevich** [comment]
Hi, please show me your Xaml and Code

**Comment by programmingworld1** [comment]
Same issue here

**Comment by programmingworld1** [comment]
Would like to make my stacklayout clickable (and show a nice gray blink when clicking), I thought the following would work? (I also added TouchEffectPreserver.Preserve() to the native projects) 
    
```xaml
<StackLayout
            touch:TouchEff.PressedScale="1.2"
            touch:TouchEff.RippleCount="1"
            touch:TouchEff.PressedRotation="10"
            touch:TouchEff.PressedRotationX="15"
            touch:TouchEff.PressedRotationY="15"
            touch:TouchEff.PressedTranslationX="5"
            touch:TouchEff.PressedTranslationY="5"
            touch:TouchEff.PressedAnimationDuration="500"
            touch:TouchEff.RegularAnimationDuration="500"
            touch.TouchEff.Command="{Binding Command}">>

                        <StackLayout BackgroundColor="{Binding DriverActivity.IsPriority, Converter={StaticResource ActivityStatusToBackgroundColorConverter}}" Orientation="Horizontal" Padding="10">

                            <customcontrols:LicensePlate IsVisible="{Binding LicensePlate.VehicleLicensePlate, Converter={StaticResource IsVisibleStringToBoolValueConverter}}" ControlTextColor="Black" ControlText="{Binding LicensePlate, Converter={StaticResource LicensePlateValueConverter}}"></customcontrols:LicensePlate>
                            <!--<ffimageloadingsvg:SvgCachedImage WidthRequest="25" HeightRequest="25" Source="{Binding DriverActivity.ActivityType, Converter={StaticResource JobActivityTypeToImageResourceValueConverter}}" />-->
                            <Label VerticalOptions="Center" LineBreakMode="TailTruncation" Text="{Binding DriverActivity.JobType, Converter={StaticResource JobTypeToLabelValueConverter}}" Style="{StaticResource DefaultLabelStyle}" TextColor="{Binding DriverActivity.IsPriority, Converter={StaticResource ActivityStatusToTextColorValueConverter}}"></Label>
                            <Label VerticalOptions="Center" LineBreakMode="TailTruncation" Text="{Binding DriverActivity.ActivityType, Converter={StaticResource ActivityTypeToLabelValueConverter}}" Style="{StaticResource DefaultLabelStyle}" TextColor="{Binding DriverActivity.IsPriority, Converter={StaticResource ActivityStatusToTextColorValueConverter}}" IsVisible="{Binding DriverActivity.JobActivityType, Converter={StaticResource IsVisibleEnumToBoolValueConverter}}"></Label>
                            <Label VerticalOptions="Center" LineBreakMode="TailTruncation" TextColor="{Binding DriverActivity.IsPriority, Converter={StaticResource ActivityStatusToTextColorValueConverter}}" Style="{StaticResource DefaultLabelStyle}" Text="{Binding DriverActivity.ImDetails.Description}" IsVisible="{Binding Description.ImDetails.Description, Converter={StaticResource IsVisibleStringToBoolValueConverter}}"></Label>
                        </StackLayout>
        </StackLayout>
```

**Comment by AndreiMisiukevich** [comment]
@programmingworld1 does Command exist in binding context?

iOS or Android?

**Comment by programmingworld1** [comment]
@AndreiMisiukevich The command exists indeed, this problem occurs for both ios and android

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich The command exists indeed, this problem occurs for both ios and android

And you use latest version, right?

**Comment by programmingworld1** [comment]
@AndreiMisiukevich  Yep, I am. I just installed it yesterday.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich Yep, I am. I just installed it yesterday.

touch.TouchEff.Command
Should be
touch:TouchEff.Command

**Comment by programmingworld1** [comment]
@AndreiMisiukevich Indeed, I changed that to ":". But that doesn't work.. It shows a background color on the stacklayout but does nothing when I click on it. Maybe the problem is bigger, because the gesturerecognizer from xamarin.forms doesnt work neither, not even on a normal label.

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/81402022-45e4b000-9139-11ea-929b-500465666305.png)


Works fine for me

**Comment by AndreiMisiukevich** [comment]
@programmingworld1 perhaps the view cannot find your Command in binding context.

You can build a small sample with the issue where GestureRecognizer works, but this package doesn't.

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich Indeed, I changed that to ":". But that doesn't work.. It shows a background color on the stacklayout but does nothing when I click on it. Maybe the problem is bigger, because the gesturerecognizer from xamarin.forms doesnt work neither, not even on a normal label.

You can run samples in this repository and play there. Because I cannot reproduce the issue.
Would be great to have a sample

**Comment by programmingworld1** [comment]
@AndreiMisiukevich Oke, I will have a look at it!

**Comment by programmingworld1** [comment]
@AndreiMisiukevich Thank you veyr much for your help, it works! The problem was indeed that I used the wrong bindingcontext.. Now I refer to the page bindingcontext instead of the bindingcontext if the item i nthe collectionview, my bad!
