### ISSUE TITLE
Long Press [Enhancement]  

### ISSUE THREAD

**Issue by ElishaMisoi** [AndreiMisiukevich/TouchEffect#58]
Would be really great if you added a long press command binding.

**Comment by AswinPG** [comment]
I did something to achieve long press. Which I think is really lazy coding. I look at the touch state and while the state is pressed I start a timer. if the timer exceeds a particular value then long press will be fired. If this implementation is good enough I'd like to create a PR. But I think that I'm doing it wrong. If someone could show me the right way I can try that and create a good PR with the correct implementation

**Comment by AndreiMisiukevich** [comment]
> I did something to achieve long press. Which I think is really lazy coding. I look at the touch state and while the state is pressed I start a timer. if the timer exceeds a particular value then long press will be fired. If this implementation is good enough I'd like to create a PR. But I think that I'm doing it wrong. If someone could show me the right way I can try that and create a good PR with the correct implementation

Why not. It could work. Just need to make sure that visual works as expected + Long press is not fired several times )

**Comment by AswinPG** [comment]
> > I did something to achieve long press. Which I think is really lazy coding. I look at the touch state and while the state is pressed I start a timer. if the timer exceeds a particular value then long press will be fired. If this implementation is good enough I'd like to create a PR. But I think that I'm doing it wrong. If someone could show me the right way I can try that and create a good PR with the correct implementation
> 
> Why not. It could work. Just need to make sure that visual works as expected + Long press is not fired several times )

Ok. I'll PR as soon as I am free then

**Comment by AndreiMisiukevich** [comment]
Implemented :)

**Comment by AswinPG** [comment]
Oops. It was a really busy week. @AndreiMisiukevich Awesome as always. You are great
