### ISSUE TITLE
TouchEff.Command should be optional

### ISSUE THREAD

**Issue by YZahringer** [AndreiMisiukevich/TouchEffect#62]
Currently if no `Command` is specified, the status is considered disabled.

In my opinion, if no `Command` is specified, the component should react of `TouchEffect`, like a `Button` without `Command`.

`CanExecute` should return `True` when `Command` is `null`?
https://github.com/AndreiMisiukevich/TouchEffect/blob/f1e78064388b632aee79d6318eb25a82cf0c77e0/TouchEffect/TouchEff.cs#L917

**Comment by AndreiMisiukevich** [comment]
@YZahringer probably you are right. Feel free to make such PR

```csharp
(Command?.CanExecute(CommandParameter) ?? true; 
```
