### ISSUE TITLE
Multiple overlapping animations

### ISSUE THREAD

**Issue by JKorf** [AndreiMisiukevich/TouchEffect#66]
Hi, thanks for your package.
I have a problem when trying to do 2 animations on 2 different controls which are on top of eachother. I have an image control and on top of that an 0.5 opacity content view with a black background to make the image sort of faded. 

My goal is to do 2 things when the image is pressed:
1. Lower the opacity of the overlay to light up the image
2. Scale up the image to give a slight zoom effect.

Now indifidually these animation work. But when I try to activate them both only 1 seems to work.
Am I doing something wrong or is this not supported?

Code:
````

<?xml version="1.0" encoding="UTF-8"?>
<Grid xmlns="http://xamarin.com/schemas/2014/forms" 
      xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
      xmlns:touchEffect="clr-namespace:TouchEffect;assembly=TouchEffect"
      x:Class="HomeBase.App.Controls.RoomControl"
      x:Name="This">

    <Grid.RowDefinitions>
        <RowDefinition></RowDefinition>
        <RowDefinition></RowDefinition>
        <RowDefinition></RowDefinition>
    </Grid.RowDefinitions>

    <Grid.ColumnDefinitions>
        <ColumnDefinition></ColumnDefinition>
        <ColumnDefinition></ColumnDefinition>
        <ColumnDefinition></ColumnDefinition>
    </Grid.ColumnDefinitions>


    <Image Grid.RowSpan="3"
           Grid.ColumnSpan="3"
           Aspect="AspectFill"
           touchEffect:TouchEff.RegularAnimationDuration="100" 
           touchEffect:TouchEff.PressedScale="1.1" 
           touchEffect:TouchEff.RegularScale="1.0" 
           touchEffect:TouchEff.PressedAnimationDuration="100"
           Source="{Binding Image, Source={x:Reference This}}">
    </Image>

    <ContentView
        Grid.RowSpan="3"
        Grid.ColumnSpan="3" 
        touchEffect:TouchEff.PressedAnimationDuration="100"
        touchEffect:TouchEff.PressedOpacity="0.3"
        touchEffect:TouchEff.RegularOpacity="0.5"
        touchEffect:TouchEff.RegularAnimationDuration="100"
        BackgroundColor="Black">
    </ContentView>

    <Label Margin="10" 
           TextColor="#eee"
           Text="{Binding Name, Source={x:Reference This}}">
    </Label>

</Grid>

````

**Comment by AndreiMisiukevich** [comment]
That's possible, but it will be quite tricky.
You should bind "State" of your bottom view to "State" of the top one.

**Comment by AndreiMisiukevich** [comment]
Something similar to https://github.com/AndreiMisiukevich/TouchEffect/issues/45#issuecomment-595465875

**Comment by JKorf** [comment]
Thanks, that way I can indeed change both controls on press, however there is no animation. Any solution for that?

**Comment by AndreiMisiukevich** [comment]
> Thanks, that way I can indeed change both controls on press, however there is no animation. Any solution for that?

I am afraid you should use "code" :)

Observer **State** property of top and set it to the bottom one.
Does it make sense?)

**Comment by JKorf** [comment]
I got it working thanks :)

For anyone having the same issue, this is my code animating 2 child controls when a parent is touched.

The control:
````
<?xml version="1.0" encoding="UTF-8"?>
<Grid xmlns="http://xamarin.com/schemas/2014/forms" 
      xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
      xmlns:touchEffect="clr-namespace:TouchEffect;assembly=TouchEffect"
      xmlns:controls="clr-namespace:HomeBase.App.Controls;assembly=HomeBase.App"
      xmlns:triggerActions="clr-namespace:HomeBase.App.TriggerActions;assembly=HomeBase.App"
      x:Class="HomeBase.App.Controls.RoomControl"
      x:Name="This">

    <Grid.RowDefinitions>
        <RowDefinition></RowDefinition>
        <RowDefinition></RowDefinition>
        <RowDefinition></RowDefinition>
    </Grid.RowDefinitions>

    <Grid.ColumnDefinitions>
        <ColumnDefinition></ColumnDefinition>
        <ColumnDefinition></ColumnDefinition>
        <ColumnDefinition></ColumnDefinition>
    </Grid.ColumnDefinitions>

    <Grid.Effects>
        <touchEffect:TouchEff />
    </Grid.Effects>

    <Grid.Triggers>
        <Trigger Property="touchEffect:TouchEff.State" Value="Pressed" TargetType="Grid">
            <Setter Property="ClassId" Value="Pressed" />
        </Trigger>
    </Grid.Triggers>

    <Image Grid.RowSpan="3"
           Grid.ColumnSpan="3"
           Aspect="AspectFill"
           Source="{Binding Image, Source={x:Reference This}}">
        <Image.Triggers>
            <DataTrigger Binding="{Binding Source={x:Reference This}, Path=ClassId}" TargetType="Image" Value="Pressed">
                <DataTrigger.EnterActions >
                    <triggerActions:ScaleTriggerAction From="1.0" To="1.1" AnimationLength="50"/>
                </DataTrigger.EnterActions>
                <DataTrigger.ExitActions >
                    <triggerActions:ScaleTriggerAction From="1.1" To="1.0" AnimationLength="50" />
                </DataTrigger.ExitActions>
            </DataTrigger>
        </Image.Triggers>
    </Image>

    <ContentView
        Grid.RowSpan="3"
        Grid.ColumnSpan="3" 
        Opacity="0.5"
        BackgroundColor="Black">
        <ContentView.Triggers>
            <DataTrigger Binding="{Binding Source={x:Reference This}, Path=ClassId}" TargetType="ContentView" Value="Pressed">
                <DataTrigger.EnterActions >
                    <triggerActions:FadeTriggerAction From="0.5" To="0.2" AnimationLength="50" />
                </DataTrigger.EnterActions>
                <DataTrigger.ExitActions >
                    <triggerActions:FadeTriggerAction From="0.2" To="0.5" AnimationLength="50" />
                </DataTrigger.ExitActions>
            </DataTrigger>
        </ContentView.Triggers>
    </ContentView>
</Grid>
````

TriggerAction:
````C#
public class FadeTriggerAction : TriggerAction<VisualElement>
    {
        public double From { set; get; }
        public double To { set; get; }
        public uint AnimationLength { get; set; }

        protected override void Invoke(VisualElement sender)
        {
            sender.Animate("FadeTriggerAction", new Animation((value) =>
                {
                    var delta = To - From;
                    value = delta * value;

                    sender.Opacity = From + value;
                }),
                length: AnimationLength,
                easing: Easing.Linear);
        }
    }
````

**Comment by AndreiMisiukevich** [comment]
> I got it working thanks :)
> 
> For anyone having the same issue, this is my code animating 2 child controls when a parent is touched.
> 
> The control:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Grid xmlns="http://xamarin.com/schemas/2014/forms" 
>       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>       xmlns:touchEffect="clr-namespace:TouchEffect;assembly=TouchEffect"
>       xmlns:controls="clr-namespace:HomeBase.App.Controls;assembly=HomeBase.App"
>       xmlns:triggerActions="clr-namespace:HomeBase.App.TriggerActions;assembly=HomeBase.App"
>       x:Class="HomeBase.App.Controls.RoomControl"
>       x:Name="This">
> 
>     <Grid.RowDefinitions>
>         <RowDefinition></RowDefinition>
>         <RowDefinition></RowDefinition>
>         <RowDefinition></RowDefinition>
>     </Grid.RowDefinitions>
> 
>     <Grid.ColumnDefinitions>
>         <ColumnDefinition></ColumnDefinition>
>         <ColumnDefinition></ColumnDefinition>
>         <ColumnDefinition></ColumnDefinition>
>     </Grid.ColumnDefinitions>
> 
>     <Grid.Effects>
>         <touchEffect:TouchEff />
>     </Grid.Effects>
> 
>     <Grid.Triggers>
>         <Trigger Property="touchEffect:TouchEff.State" Value="Pressed" TargetType="Grid">
>             <Setter Property="ClassId" Value="Pressed" />
>         </Trigger>
>     </Grid.Triggers>
> 
>     <Image Grid.RowSpan="3"
>            Grid.ColumnSpan="3"
>            Aspect="AspectFill"
>            Source="{Binding Image, Source={x:Reference This}}">
>         <Image.Triggers>
>             <DataTrigger Binding="{Binding Source={x:Reference This}, Path=ClassId}" TargetType="Image" Value="Pressed">
>                 <DataTrigger.EnterActions >
>                     <triggerActions:ScaleTriggerAction From="1.0" To="1.1" AnimationLength="50"/>
>                 </DataTrigger.EnterActions>
>                 <DataTrigger.ExitActions >
>                     <triggerActions:ScaleTriggerAction From="1.1" To="1.0" AnimationLength="50" />
>                 </DataTrigger.ExitActions>
>             </DataTrigger>
>         </Image.Triggers>
>     </Image>
> 
>     <ContentView
>         Grid.RowSpan="3"
>         Grid.ColumnSpan="3" 
>         Opacity="0.5"
>         BackgroundColor="Black">
>         <ContentView.Triggers>
>             <DataTrigger Binding="{Binding Source={x:Reference This}, Path=ClassId}" TargetType="ContentView" Value="Pressed">
>                 <DataTrigger.EnterActions >
>                     <triggerActions:FadeTriggerAction From="0.5" To="0.2" AnimationLength="50" />
>                 </DataTrigger.EnterActions>
>                 <DataTrigger.ExitActions >
>                     <triggerActions:FadeTriggerAction From="0.2" To="0.5" AnimationLength="50" />
>                 </DataTrigger.ExitActions>
>             </DataTrigger>
>         </ContentView.Triggers>
>     </ContentView>
> </Grid>
> ```
> 
> TriggerAction:
> 
> ```cs
> public class FadeTriggerAction : TriggerAction<VisualElement>
>     {
>         public double From { set; get; }
>         public double To { set; get; }
>         public uint AnimationLength { get; set; }
> 
>         protected override void Invoke(VisualElement sender)
>         {
>             sender.Animate("FadeTriggerAction", new Animation((value) =>
>                 {
>                     var delta = To - From;
>                     value = delta * value;
> 
>                     sender.Opacity = From + value;
>                 }),
>                 length: AnimationLength,
>                 easing: Easing.Linear);
>         }
>     }
> ```

awesome ) thanks
