### ISSUE TITLE
Thank you ! (And a little suggestion regarding Visual Material)

### ISSUE THREAD

**Issue by HakanCelikMKA** [AndreiMisiukevich/TouchEffect#72]
Excellent job Sir, you've just saved my day with your library. Thank you !

By the way, would you consider making it compatible with Visual Material in the future ?

**Comment by AndreiMisiukevich** [comment]
Hi) thanks
I'm glad to hear it.

This is a good question. I haven't thought about it yet.
Probably I will add this library to https://github.com/xamarin/XamarinCommunityToolkit

**Comment by HakanCelikMKA** [comment]
You are very welcome. I think, contributing it to Community Toolkit would be a good idea. I've found TouchEffect after a lot of search. If it is in the toolkit, more people would be able to find and use it. Hopefully they (including myself) will contribute too.

Thanks for your efforts.

**Comment by AndreiMisiukevich** [comment]
@HakanCelikMK1 https://github.com/xamarin/XamarinCommunityToolkit/issues/200 👍
