### ISSUE TITLE
PressedBackgroundColor on Frame

### ISSUE THREAD

**Issue by 1grzyb1** [AndreiMisiukevich/TouchEffect#73]
After aplying PressedBackgroundColor on Frame it removes Frames shadow from HasShadow property.
I checked and PressedOpacity doesn't remove this effect.

**Comment by AndreiMisiukevich** [comment]
iOS, right?

I presume it's XF bug (because PressedBackgroundColor just changes BackgroundColor of the view)

**Comment by AndreiMisiukevich** [comment]
You can try to create a frame, then change its background color in runtime and see if the HasShadow has broken or not

**Comment by 1grzyb1** [comment]
Oposite on iOS shadow is rendering but on android don't. I tried to change BackgroundColor in runtime but it doesn't solve the issue.

**Comment by AndreiMisiukevich** [comment]
I guess that's XF issue.
Do shadows render without TouchEff?
What will happen if you change BackgroundColor by button click (Without TouchEff)
If the issue still exists, then it's not related to TouchEff

**Comment by 1grzyb1** [comment]
When I change Background color of Frame on button click then Shadow on frame still appear.

**Comment by AndreiMisiukevich** [comment]
Well. need to check. I thought Frame on Android doesn't have a shadow at all

**Comment by AndreiMisiukevich** [comment]
Fixed
