### ISSUE TITLE
Touch Effect Not working on IOS

### ISSUE THREAD

**Issue by ShamineDsouza** [AndreiMisiukevich/TouchEffect#74]
It does not trigger , nor does it show any effect .
Works perfectly in android.

  <StackLayout HorizontalOptions="CenterAndExpand" VerticalOptions="StartAndExpand" x:Name="stkLayNominee" x:FieldModifier="Public"   
                        toucheff:TouchEff.NativeAnimation="True"
                         toucheff:TouchEff.NativeAnimationShadowRadius="80"
                        toucheff:TouchEff.NativeAnimationColor="{ DynamicResource BaseTextColor }"
                         Margin="0,0,0,0" >

  TouchEffectPreserver.Preserve();
   LoadApplication(new App());

Please help

**Comment by AndreiMisiukevich** [comment]
Please show me your xaml/code.
Or even better -- build a small sample.

**Comment by AndreiMisiukevich** [comment]
NativeAnimation=True

**Comment by ShamineDsouza** [comment]
[File.zip](https://github.com/AndreiMisiukevich/TouchEffect/files/5231033/File.zip)
PLeaese find the xaml file

**Comment by ShamineDsouza** [comment]
I have already kept the NativeAnimation=True

**Comment by AndreiMisiukevich** [comment]
I cannot reproduce it on my sample.
You can try it yourself on my sample project.

Can you build a small project with very simple example showing this bug. Or even better try to replicate this problem on my samples.

**Comment by ShamineDsouza** [comment]
Issue was that there was something overlapping the stack layout. Resolved by sending to background . Effect working Fine . 

Thank You  :)

**Comment by AndreiMisiukevich** [comment]
perfect)
