### ISSUE TITLE
If parent element have gesture and child element have touch effect disabled the child element override parent's gesture

### ISSUE THREAD

**Issue by KyrillosS25** [AndreiMisiukevich/TouchEffect#78]
Hello, 
I have 2 stacklayout the parent stack have tap gesture and child stack have touch effect with "IsAvailable = 'False'", when tapping on child stack nothing happens.

could I add/remove touch effect form code behind?

![ezgif-7-6981f1ba6b72](https://user-images.githubusercontent.com/56297254/96580752-0bcb2d00-12d9-11eb-8ad5-0c3f0a99ee24.gif)

Code : 
`
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:touch="clr-namespace:TouchEffect;assembly=TouchEffect"
             x:Class="App1.MainPage">

    <StackLayout BackgroundColor="Red" HeightRequest="100" WidthRequest="100"> 

        <StackLayout  BackgroundColor="Blue" HeightRequest="50" WidthRequest="50" 
                         touch:TouchEff.NativeAnimation="False"
                         touch:TouchEff.IsAvailable="False"
                         touch:TouchEff.NativeAnimationShadowRadius="10"
                         touch:TouchEff.NativeAnimationColor="Gray">
            
        </StackLayout>
        <StackLayout.GestureRecognizers>
            <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
        </StackLayout.GestureRecognizers>
    </StackLayout>
</ContentPage>
`

**Comment by AndreiMisiukevich** [comment]
Try to set InputTransparent to your child StackLayout

**Comment by AndreiMisiukevich** [comment]
That's not TouchEff problem. If you remove TouchEffect at all and just leave a child stack layout the behavior will remain the same

**Comment by KyrillosS25** [comment]
> Try to set InputTransparent to your child StackLayout

I tried it and got the same behavior

**Comment by KyrillosS25** [comment]
> That's not TouchEff problem. If you remove TouchEffect at all and just leave a child stack layout the behavior will remain the same

I removed TouchEff from child stack and got the tapped event of the parent, I think that TouchEff somehow override the parent event event if  "IsAvailable='False'"

![ezgif-7-6981f1ba6b72](https://user-images.githubusercontent.com/56297254/96683911-11794f00-137b-11eb-83e8-844a9187996b.gif)



`
<StackLayout BackgroundColor="Red" HeightRequest="100" WidthRequest="100"> 

        <StackLayout  BackgroundColor="Blue" HeightRequest="50" WidthRequest="50" 
                      
                         >
            
        </StackLayout>
        <StackLayout.GestureRecognizers>
            <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"></TapGestureRecognizer>
        </StackLayout.GestureRecognizers>
    </StackLayout>
`

**Comment by AndreiMisiukevich** [comment]
Have you tried to set InputTransparent = true?

**Comment by KyrillosS25** [comment]
yes

**Comment by AndreiMisiukevich** [comment]
Confirmed that's a bug.

Well, there is a workaround. You can remove the effect from code

```
var effects = view.Effects.OfType<TouchEff>().ToArray();
foreach (var effect in effects)
    view.Effects.Remove(effect);
```

**Comment by KyrillosS25** [comment]
okay thanks, I'll try that.

**Comment by KyrillosS25** [comment]
@AndreiMisiukevich 
the workaround worked. but can I add effects to view from code instead of removing them ?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> the workaround worked. but can I add effects to view from code instead of removing them ?

Yes, sure you can :)

```
view.Effects.Add(new TouchEff());
TouchEff.SetCommand(view, new Command()); // etc.
```

**Comment by KyrillosS25** [comment]
Thanks

**Comment by AndreiMisiukevich** [comment]
Now works fine with IsAvailable=False
