### ISSUE TITLE
Ripple Effect - Fade Duration

### ISSUE THREAD

**Issue by sethom** [AndreiMisiukevich/TouchEffect#8]
Hi, I'm trying to do a ripple effect as described here: https://github.com/AndreiMisiukevich/TouchEffect/issues/5 ... I'm going for something that should look like what is seen here:  https://github.com/mrxten/XamEffects..  However, in "issues/5" (above link) you say:

"You should use TouchView (more info in Readme file on main page of the project)
Use FadeDuration/FadeEasing/RecoverDuration/RecoverEasing for achieving the same behavior."

I'm using TouchView with version 2.0.3 and using FadeDuration gives me the error "No property, bindable property, or event found for "FadeDuration", or mismatching type between value and property".. 

Has this property not be released yet? ..Here's my code:
```xaml
 <touch:TouchView
            PressedAnimationDuration="250"
            RegularAnimationDuration="250"
            RippleCount="-1"
            FadeDuration="250"
            RecoverDuration="250" 
            Padding="10, 5"
            BackgroundColor="Red"
            VerticalOptions="CenterAndExpand"
            HorizontalOptions="CenterAndExpand"
            Completed="Handle_TouchCompleted">

            <Label Text="CLICK ME" 
                   TextColor="White" 
                   FontSize="60"/>
            
        </touch:TouchView>
```

**Comment by AndreiMisiukevich** [comment]
Hi )
Have you checked documentation ?)

Here is the list of all properties with description:
https://github.com/AndreiMisiukevich/TouchEffect#all-properties

**Comment by AndreiMisiukevich** [comment]
Please, use ```PressedAnimationDuration``` and ```RegularAnimationDuration``` :)

**Comment by AndreiMisiukevich** [comment]
Thanks for feedback :) i updated that issue

have a good day!

**Comment by sethom** [comment]
Thanks! I didn't realize PressedAnimationDuration and RegularAnimationDuration where to be used in place of FadeDuration and RecoverDuration.
