### ISSUE TITLE
Style template not working

### ISSUE THREAD

**Issue by Suplanus** [AndreiMisiukevich/TouchEffect#82]
Hi,
first of all a big thank you to this great library.

I try to create a style template for my touchable controls:

```xml
<Style x:Key="TapableControl" TargetType="{x:Type ContentView}">
    <Setter Property="touch:TouchEff.RegularAnimationDuration" Value="100" />
    <Setter Property="touch:TouchEff.PressedScale" Value="0.95" />
</Style>
```

But this is not possible because it's not writable.

**Comment by Suplanus** [comment]
I think it's only an error in VS, but it's building and works.

![image](https://user-images.githubusercontent.com/2002916/98550790-d2b12780-229c-11eb-88ab-9137f7c48e80.png)

**Comment by AndreiMisiukevich** [comment]
> I think it's only an error in VS, but it's building and works.
> 
> ![image](https://user-images.githubusercontent.com/2002916/98550790-d2b12780-229c-11eb-88ab-9137f7c48e80.png)

Hmmm, super strange.

**Comment by Suplanus** [comment]
Could you reproduce the error?

**Comment by AndreiMisiukevich** [comment]
> Could you reproduce the error?

No, I cannot. I guess you made a mistake

```TargetType="StackLayout"```

```xaml
        <Style x:Key="ResStyle" TargetType="StackLayout">
            <Setter Property="AbsoluteLayout.LayoutBounds" Value="0,0,1,1" />
            <Setter Property="touch:TouchEff.AnimationDuration" Value="1" />
        </Style>
```

**Comment by AndreiMisiukevich** [comment]
No error even with your sample (VS for Mac 2019)

![image](https://user-images.githubusercontent.com/10124814/98554693-0f3b4e00-22b2-11eb-8d05-34afdff45b4e.png)

**Comment by AndreiMisiukevich** [comment]
Well, as you said, it's VS issue 

Maybe try to update your VS, clean the project (remove all bin and obj folder) and restart VS and try again.
Otherwise, this bug should be reported to VS team

My VS for Mac:
![image](https://user-images.githubusercontent.com/10124814/98554956-63463280-22b2-11eb-811c-0ddaa49edd81.png)
