### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by maxkoshevoi** [AndreiMisiukevich/TouchEffect#83]
Hi, how can I achieve ripple effect (like in this NuGet: https://github.com/mrxten/XamEffects)?
I'm creating a custom list and existing ListView is xamarin displays ripple effect while item is pressed (at least on android). I want to to exactly the same effect. Is it possible with this NuGet (preferably without custom code)?

**Comment by AndreiMisiukevich** [comment]
Hi, yes. Use "NativeAnimation = True". That's it
