### ISSUE TITLE
[Bug] Native animation doesn't respect device theme

### ISSUE THREAD

**Issue by maxkoshevoi** [AndreiMisiukevich/TouchEffect#84]
**Issue**

Here is a compaction of animation of list view and animation from this nuget in light and dark themes:
https://photos.app.goo.gl/fvH5zgATE2oj2BMc7

In dark theme color stays the same and becomes not visible.

**Workaround**

Manually set the color: `<Setter Property="touch:TouchEff.NativeAnimationColor" Value="#40808080"/>`
(`40808080 `looks kinda the same for white and dark background and kinda matches android animation color)

**Comment by AndreiMisiukevich** [comment]
Hi, what will happen if you

1) Close the app (and remove from the memory)
2) Set the dark theme
3) Open the app (like cold start)

Will the bug remain?

**Comment by AndreiMisiukevich** [comment]
I guess, yes, it will remain.

Well, https://github.com/AndreiMisiukevich/TouchEffect/blob/master/TouchEffect.Droid/PlatformTouchEff.cs#L324

Here is the root cause. We should force to update the color (and choose different color) when the app theme changed
