### ISSUE TITLE
Touch effect after X milliseconds or after completed event

### ISSUE THREAD

**Issue by leonardbarbu** [AndreiMisiukevich/TouchEffect#85]
Hello,
It is somehow possible to see the touch effect only if it is not cancelled within the first X milliseconds?
Or it is possible to see the touch effect only if the completed event is fired?

I am trying to have a ListView feeling using a StackLayout with BindableLayout ItemsSource because the StackLayout is more performant on scrolling.
Thanks.

**Comment by AndreiMisiukevich** [comment]
Hi, for now, such behavior can be achieved only by the user's code.
You can observe "State" property and change UI.

For "NativeAnimation" it's impossible.

**Comment by leonardbarbu** [comment]
I have tried in code behind in the Completed event to use "SetNativeAnimation" with True for the sender (a Frame) and after to set the Status or the State for that sender but didn't succeeded to see the effect.
Thanks for clarification.
