### ISSUE TITLE
add effect button to any content

### ISSUE THREAD

**Issue by KevinAnass** [AndreiMisiukevich/TouchEffect#86]
how I can add the same effect like this with your nugget 
thanks in advance 

https://github.com/mrxten/XamEffects/blob/master/images/touch/android.gif

**Comment by AndreiMisiukevich** [comment]
TouchEffect was merged to XamarinCommunityToolkit https://github.com/xamarin/XamarinCommunityToolkit/pull/566 I highly recommend to use TouchEffect from XCT

**Comment by AndreiMisiukevich** [comment]
But, just set NativeAnimation=True and NativeColor = Color.Red

**Comment by KevinAnass** [comment]
thank you so much for your answer
