### ISSUE TITLE
[Question] Toucheffekt like ListView ViewCell

### ISSUE THREAD

**Issue by AlleSchonWeg** [AndreiMisiukevich/TouchEffect#87]
Hi,
i try to create a effect in a StackLayout like the touch on a Listview item.
On iOS/Android the whole row gives feedback in a ListView item. 
Is this possible?
Thank you

**Comment by AndreiMisiukevich** [comment]
Hi, yes. Set NativeAnimation=True

**Comment by AlleSchonWeg** [comment]
Thanks.
i tried this already, but the effect is only on the labels (iOS). Not on the StackLayout. Sample:
```
				<StackLayout touch:TouchEff.NativeAnimation="True">
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
							</StackLayout>
```
Sample Listview:
```
							<ListView 
									  SeparatorVisibility="None"
									  Margin="0"
									  HeightRequest="60"
									  VerticalOptions="Start"
									  HasUnevenRows="True"
									  SelectionMode="None"
									  BackgroundColor="Transparent"
									  ItemsSource="{Binding Items}">
								<ListView.ItemTemplate>
									<DataTemplate>
										<ViewCell>
				            <StackLayout>
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
							</StackLayout>
										</ViewCell>
									</DataTemplate>
								</ListView.ItemTemplate>
							</ListView>
```

**Comment by AndreiMisiukevich** [comment]
Set NativeColor :)

BTW, this project will be closed soon.
I propose to use https://github.com/xamarin/XamarinCommunityToolkit

I moved TouchEffect there

**Comment by AlleSchonWeg** [comment]
@AndreiMisiukevich
If i set the NativeAnimationColor:
```
							<StackLayout touch:TouchEff.NativeAnimation="True"
										 touch:TouchEff.NativeAnimationColor="Green">
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
								<Label Text="Dies ist ein TEst"
									   HorizontalTextAlignment="Start"
									   VerticalTextAlignment="Center"
									   LineBreakMode="TailTruncation"
									   MaxLines="3"></Label>
							</StackLayout>
```

the whole Stacklayout has the effect. Where i know whats the default color is?

**Comment by AlleSchonWeg** [comment]
> Set NativeColor :)
> 
> BTW, this project will be closed soon.
> I propose to use [xamarin/XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit)
> 
> I moved TouchEffect there

I know, but there is no release version yet.

**Comment by AndreiMisiukevich** [comment]
DefaultColor is **No color** ) Just changes the opacity of view

**Comment by AlleSchonWeg** [comment]
> DefaultColor is **No color** ) Just changes the opacity of view

Thanks again. ;)
With default i mean the default system color for the toucheffect from the device/os. Sorry, for asking stupid questions, but i'm using your effect for the first time. :)
I tried android and the effect was what i want, without changeing opacity or setting NativeAnimationColor. Only set NativeAnimation=True works.

**Comment by AndreiMisiukevich** [comment]
The problem that iOS doesn't have "native" color :)
You can see how buttons works (it's just tappable text without borders).
