### ISSUE TITLE
Effect Not compatible With the rounded Image 

### ISSUE THREAD

**Issue by KevinAnass** [AndreiMisiukevich/TouchEffect#88]
Effect Not compatible With the rounded Image 

when I want to add the effect native to circle image I want to show the effect just in the image, not like that 
![2fe72bcc-4ea7-47ef-bbcf-1d7664c935fc](https://user-images.githubusercontent.com/59505755/101290372-15b1dc80-3802-11eb-8d53-61822e879165.jpg)
is that possible?

**Comment by AndreiMisiukevich** [comment]
This effect is merged into XamarinCommunityToolkit. It's better to ask there)

But, I think, it depends on how did you implement the circle image) Frame + Image? Or new xamarin shapes API?
I suggest you try both
Or try to set **NativeAnimationRadius**

**Comment by KevinAnass** [comment]
thank you so much Andrei Misiukevich
