### ISSUE TITLE
Support UWP Platform

### ISSUE THREAD

**Issue by YZahringer** [AndreiMisiukevich/TouchEffect#9]
Support for the UWP platform would be useful. With mouse over, entered, exited, moved, ...

**Comment by AndreiMisiukevich** [comment]
Does anybody want to contribute?

**Comment by MitchBomcanhao** [comment]
Until v3, UWP kind of worked, ie you didn't get visible effects but tapping the touchview control did trigger the completed event.

Having switched to the effect approach, it seems like it might be simpler to get the UWP version working. I've quickly tried to create my own effect file with a similar pattern and include it in my project, and it *just worked*. Now, I'm sure that there are probably other events to subscribe to, but what I've got here allows for the three basic states to be triggered.

```
using TouchEffect;
using TouchEffect.Extensions;
using TouchEffect.Enums;
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using MyNamespace.Effects;

[assembly: ResolutionGroupName(nameof(TouchEffect))]
[assembly: ExportEffect(typeof(PlatformTouchEff), nameof(TouchEff))]

namespace MyNamespace.Effects
{
    /// <summary>
    /// This extends the TouchEffect package to also work on UWP.
    /// </summary>
    class PlatformTouchEff : PlatformEffect
    {
        private TouchEff _effect;

        protected override void OnAttached()
        {
            _effect = Element.GetTouchEff();
            _effect.Control = Element as VisualElement;
            _effect.ForceUpdateState(false);

            if (Container != null)
            {
                Container.Tapped += Container_Tapped;
                Container.PointerPressed += Container_PointerPressed;
                Container.PointerExited += Container_PointerExited;
            }
        }

        protected override void OnDetached()
        {
            _effect.Control = null;
            _effect = null;
            if (Container != null)
            {
                Container.Tapped -= Container_Tapped;
                Container.PointerPressed -= Container_PointerPressed;
                Container.PointerExited -= Container_PointerExited;
            }
        }

        private void Container_Tapped(object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
        {
            Element.GetTouchEff().HandleTouch(TouchStatus.Completed);
            e.Handled = true;
        }

        private void Container_PointerExited(object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs e)
        {
            Element.GetTouchEff().HandleTouch(TouchStatus.Canceled);
            e.Handled = true;
        }

        private void Container_PointerPressed(object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs e)
        {
            Element.GetTouchEff().HandleTouch(TouchStatus.Started);
            e.Handled = true;
        }
    }
}
```

**Comment by AndreiMisiukevich** [comment]
> Until v3, UWP kind of worked, ie you didn't get visible effects but tapping the touchview control did trigger the completed event.
> 
> Having switched to the effect approach, it seems like it might be simpler to get the UWP version working. I've quickly tried to create my own effect file with a similar pattern and include it in my project, and it _just worked_. Now, I'm sure that there are probably other events to subscribe to, but what I've got here allows for the three basic states to be triggered.
> 
> ```
> using TouchEffect;
> using TouchEffect.Extensions;
> using TouchEffect.Enums;
> using Xamarin.Forms;
> using Xamarin.Forms.Platform.UWP;
> using MyNamespace.Effects;
> 
> [assembly: ResolutionGroupName(nameof(TouchEffect))]
> [assembly: ExportEffect(typeof(PlatformTouchEff), nameof(TouchEff))]
> 
> namespace MyNamespace.Effects
> {
>     /// <summary>
>     /// This extends the TouchEffect package to also work on UWP.
>     /// </summary>
>     class PlatformTouchEff : PlatformEffect
>     {
>         private TouchEff _effect;
> 
>         protected override void OnAttached()
>         {
>             _effect = Element.GetTouchEff();
>             _effect.Control = Element as VisualElement;
>             _effect.ForceUpdateState(false);
> 
>             if (Container != null)
>             {
>                 Container.Tapped += Container_Tapped;
>                 Container.PointerPressed += Container_PointerPressed;
>                 Container.PointerExited += Container_PointerExited;
>             }
>         }
> 
>         protected override void OnDetached()
>         {
>             _effect.Control = null;
>             _effect = null;
>             if (Container != null)
>             {
>                 Container.Tapped -= Container_Tapped;
>                 Container.PointerPressed -= Container_PointerPressed;
>                 Container.PointerExited -= Container_PointerExited;
>             }
>         }
> 
>         private void Container_Tapped(object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
>         {
>             Element.GetTouchEff().HandleTouch(TouchStatus.Completed);
>             e.Handled = true;
>         }
> 
>         private void Container_PointerExited(object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs e)
>         {
>             Element.GetTouchEff().HandleTouch(TouchStatus.Canceled);
>             e.Handled = true;
>         }
> 
>         private void Container_PointerPressed(object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs e)
>         {
>             Element.GetTouchEff().HandleTouch(TouchStatus.Started);
>             e.Handled = true;
>         }
>     }
> }
> ```

make PR please :)

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao are you interested in making PR ?

**Comment by MitchBomcanhao** [comment]
I wanted to get it done but am inexperienced, so spent a while figuring out how to add another project and how it is supposed to be built and I'm not sure I was entirely successful. If you feel you can get it done quickly feel free do adapt it yourself ;)

**Comment by AndreiMisiukevich** [comment]
@MitchBomcanhao btw it's done ;)

**Comment by MitchBomcanhao** [comment]
Great, I haven't had the chance to try it as I'm on holiday but will do give it a look next week 😉
