### ISSUE TITLE
Is it possible to handle when I just touch the control, not on release?

### ISSUE THREAD

**Issue by nithrous** [AndreiMisiukevich/TouchEffect#90]
After quick view I noticed that there are only 2 possible command handlers - press and long press. All they are firing when I release my finger, but I want to callback immediately when I touch - is it possible?

**Comment by AndreiMisiukevich** [comment]
Hello
This plugin was merged to Xamarin.CommunityToolkit.

You should use that nuget instead.

As far I remember it wasn't possible
