### ISSUE TITLE
Support in MAUI

### ISSUE THREAD

**Issue by judsonabraham301** [AndreiMisiukevich/TouchEffect#92]
I have used this in my project. We have PlatformTouchEff class in our project implemented it was working well. But after MAUI migration we are not able to fix errors in the PlatformTouchEff. Will there be a MAUI upgrade of the Touch Effect since I can see it is updated 4 years ago.
We are getting invalid cast exception in the following codes:
Private ViewGroup group=> Container as ViewGroup;
Var Group=(ViewGroup)sender;
What is the MAUI alternative for these codes?

**Comment by AndreiMisiukevich** [comment]
Hi, I contributed it to XCT years ago.
So, you can try XCT or maybe they migrated it to MAUI toolkit

<img width="940" alt="image" src="https://github.com/AndreiMisiukevich/TouchEffect/assets/10124814/c1222a42-466b-4c15-acaa-20059977285b">
