### ISSUE TITLE
request

### ISSUE THREAD

**Issue by BySuspect** [AndreiMisiukevich/TouchEffect#93]
can you do click effects for .net maui?

**Comment by AndreiMisiukevich** [comment]
Hello
Isn’t it available in maui community toolkit?

This plugin was merged to Xamarin community toolkit and I believe it should be migrated to Maui toolkit

**Comment by BySuspect** [comment]
I looked at the documentation and couldn't find it, I installed the kit and tried it in my project, I couldn't find it, I guess it wasn't added.

**Comment by AndreiMisiukevich** [comment]
Yeah... Have you asked them to port it?

**Comment by BySuspect** [comment]
Not yet, I wanted to ask you first since you are the real developer.

**Comment by AndreiMisiukevich** [comment]
haha, got you!

Maybe I will find some time to do it. But i don't know when. And I can't promise it.
I am not a maintainer of community toolkit for 2 years now

**Comment by AndreiMisiukevich** [comment]
https://www.linkedin.com/posts/jfversluis_release-v800-can-touch-this-touchbehavior-activity-7179475479781855235-BOhs?utm_source=share&utm_medium=member_ios
